<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(9)</name>
   <tag></tag>
   <elementGuidId>4acbafbc-8449-42c4-8088-04928837f0af</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;pageNumber\&quot;: -77884856,\n    \&quot;pageSize\&quot;: -14924174,\n    \&quot;flags\&quot;: 256,\n    \&quot;sortingOperations\&quot;: [\n        {\n            \&quot;property\&quot;: 4,\n            \&quot;orderByDirection\&quot;: 1\n        },\n        {\n            \&quot;property\&quot;: 0,\n            \&quot;orderByDirection\&quot;: 1\n        }\n    ],\n    \&quot;filteringOperations\&quot;: [\n        {\n            \&quot;property\&quot;: 64,\n            \&quot;cretiria\&quot;: \&quot;laborum minim ullamco pariatur\&quot;,\n            \&quot;comparisonType\&quot;: 7\n        },\n        {\n            \&quot;property\&quot;: 1,\n            \&quot;cretiria\&quot;: \&quot;commodo do cupidatat sint\&quot;,\n            \&quot;comparisonType\&quot;: 4\n        }\n    ],\n    \&quot;tablePreferenceId\&quot;: -60023065\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <katalonVersion>8.2.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${baseUrl}/api/identity/v${version}/Account/get</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.baseUrl</defaultValue>
      <description></description>
      <id>1b3215bc-c9e7-4f5f-8d97-fa96a87ac94c</id>
      <masked>false</masked>
      <name>baseUrl</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>77390ba0-309e-42db-b9f1-5d78f3cbce92</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
