<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Edit existing language variant</name>
   <tag></tag>
   <elementGuidId>48b2957f-a6ea-4749-863e-f21f4566516a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n  \&quot;id\&quot;: 8,\r\n  \&quot;name\&quot;: \&quot;${LangVarName}\&quot;,\r\n  \&quot;variantCode\&quot;: \&quot;${LangVarCode}\&quot;,\r\n  \&quot;languageId\&quot;: ${LangVarId}\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>ar</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <katalonVersion>8.1.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${baseUrl}/api/management/languagevariants</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.baseUrl</defaultValue>
      <description></description>
      <id>270d9cf7-5412-48f7-9708-356cc0b31676</id>
      <masked>false</masked>
      <name>baseUrl</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.LangVarName</defaultValue>
      <description></description>
      <id>19af5d69-c3fa-4dbc-9a07-8cdf6ad743ee</id>
      <masked>false</masked>
      <name>LangVarName</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.LangVarCode</defaultValue>
      <description></description>
      <id>72d7baa6-7be5-44d8-90d2-083aecb312d4</id>
      <masked>false</masked>
      <name>LangVarCode</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.LangVarId</defaultValue>
      <description></description>
      <id>91f357ec-cde6-4657-afb6-993060d9732c</id>
      <masked>false</masked>
      <name>LangVarId</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
