<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(30)</name>
   <tag></tag>
   <elementGuidId>9f6a7bb1-f0dd-4458-ad5b-a52a876d8e4a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;name\&quot;: \&quot;velit elit\&quot;,\n    \&quot;tableName\&quot;: \&quot;aliqua\&quot;,\n    \&quot;id\&quot;: 48213850,\n    \&quot;flags\&quot;: 83357403,\n    \&quot;sortingOperations\&quot;: [\n        {\n            \&quot;property\&quot;: -21028016,\n            \&quot;orderByDirection\&quot;: 1\n        },\n        {\n            \&quot;property\&quot;: 31268905,\n            \&quot;orderByDirection\&quot;: 0\n        }\n    ],\n    \&quot;filteringOperations\&quot;: [\n        {\n            \&quot;property\&quot;: -93701375,\n            \&quot;cretiria\&quot;: \&quot;cupidatat minim\&quot;,\n            \&quot;comparisonType\&quot;: 5\n        },\n        {\n            \&quot;property\&quot;: -31400067,\n            \&quot;cretiria\&quot;: \&quot;officia aliquip in laboris et\&quot;,\n            \&quot;comparisonType\&quot;: 7\n        }\n    ]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <katalonVersion>8.2.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${baseUrl}/api/identity/v${version}/TablePreferences</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.baseUrl</defaultValue>
      <description></description>
      <id>2a470d85-7474-4509-8664-544317f98b94</id>
      <masked>false</masked>
      <name>baseUrl</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.version</defaultValue>
      <description></description>
      <id>e3ce07a2-a684-4c02-8802-b497146b2489</id>
      <masked>false</masked>
      <name>version</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
